/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

/**
 *
 * @author Alina
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtIn = new javax.swing.JTextField();
        jbtnSearch = new javax.swing.JButton();
        jlblOut = new javax.swing.JLabel();
        jbtnStack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter an Integer to Search");

        jbtnSearch.setText("Search");
        jbtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchActionPerformed(evt);
            }
        });

        jlblOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbtnStack.setText("Populate Stack 0-1000 Inclusive");
        jbtnStack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnStackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtIn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnSearch))
                    .addComponent(jlblOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnStack)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnStack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblOut, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    LList list = new LList();
    
    private void jbtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchActionPerformed
        // TODO add your handling code here:     
        
        String input;
        int value;
        
         input= jtxtIn.getText();
         
        value = Integer.parseInt(input);
        
        if(list.ListSearch(list.head, value))
        {
            jlblOut.setText("The number "+ value + " has been found in the stack");
        }
        else
        {
            jlblOut.setText("The number " + value + " was not found in the stack");
        }
        
        
        
    }//GEN-LAST:event_jbtnSearchActionPerformed

    private void jbtnStackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnStackActionPerformed
        // TODO add your handling code here:
        
        list.push(385);
        list.push(14);
        list.push(341);
        list.push(891);
        list.push(197);
        list.push(816);
        list.push(961);
        list.push(48);
        list.push(778);
        list.push(227);
        list.push(405);
        list.push(611);
        list.push(484);
        list.push(195);
        list.push(512);
        list.push(752);
        list.push(845);
        list.push(705);
        list.push(504);
        list.push(15);
        list.push(513);
        list.push(91);
        list.push(192);
        list.push(318);
        list.push(101);
        list.push(764);
        list.push(745);
        list.push(948);
        list.push(625);
        list.push(540);
        list.push(675);
        list.push(447);
        list.push(779);
        list.push(554);
        list.push(221);
        list.push(936);
        list.push(341);
        list.push(756);
        list.push(401);
        list.push(170);
        list.push(252);
        list.push(290);
        list.push(201);
        list.push(657);
        list.push(436);
        list.push(665);
        list.push(69);
        list.push(72);
        list.push(856);
        list.push(537);
        list.push(12);
        list.push(346);
        list.push(806);
        list.push(172);
        list.push(309);
        list.push(368);
        list.push(848);
        list.push(405);
        list.push(242);
        list.push(968);
        list.push(10);
        list.push(888);
        list.push(527);
        list.push(186);
        list.push(161);
        list.push(342);
        list.push(527);
        list.push(970);
        list.push(301);
        list.push(30);
        list.push(850);
        list.push(527);
        list.push(943);
        list.push(414);
        list.push(720);
        list.push(389);
        list.push(972);
        list.push(423);
        list.push(817);
        list.push(46);
        list.push(198);
        list.push(361);
        list.push(458);
        list.push(511);
        list.push(91);
        list.push(829);
        list.push(674);
        list.push(409);
        list.push(203);
        list.push(153);
        list.push(112);
        list.push(679);
        list.push(4);
        list.push(789);
        list.push(498);
        list.push(503);
        list.push(297);
        list.push(342);
        list.push(62);
        list.push(718);
        
        //100 pushed to stack
        
        list.push(549);
        list.push(114);
        list.push(836);
        list.push(330);
        list.push(882);
        list.push(419);
        list.push(938);
        list.push(289);
        list.push(176);
        list.push(970);
        list.push(774);
        list.push(461);
        list.push(786);
        list.push(294);
        list.push(64);
        list.push(478);
        list.push(658);
        list.push(398);
        list.push(172);
        list.push(142);
        list.push(756);
        list.push(363);
        list.push(257);
        list.push(196);
        list.push(711);
        list.push(129);
        list.push(343);
        list.push(985);
        list.push(621);
        list.push(192);
        list.push(627);
        list.push(290);
        list.push(504);
        list.push(40);
        list.push(617);
        list.push(832);
        list.push(612);
        list.push(856);
        list.push(171);
        list.push(876);
        list.push(837);
        list.push(77);
        list.push(543);
        list.push(980);
        list.push(888);
        list.push(898);
        list.push(76);
        list.push(926);
        list.push(782);
        list.push(956);
        list.push(774);
        list.push(228);
        list.push(544);
        list.push(215);
        list.push(620);
        list.push(342);
        list.push(317);
        list.push(924);
        list.push(199);
        list.push(711);
        list.push(716);
        list.push(614);
        list.push(366);
        list.push(458);
        list.push(425);
        list.push(641);
        list.push(373);
        list.push(633);
        list.push(107);
        list.push(115);
        list.push(506);
        list.push(380);
        list.push(895);
        list.push(357);
        list.push(553);
        list.push(63);
        list.push(214);
        list.push(546);
        list.push(629);
        list.push(194);
        list.push(330);
        list.push(606);
        list.push(933);
        list.push(341);
        list.push(643);
        list.push(781);
        list.push(151);
        list.push(732);
        list.push(201);
        list.push(838);
        list.push(499);
        list.push(791);
        list.push(337);
        list.push(789);
        list.push(532);
        list.push(900);
        list.push(907);
        list.push(613);
        list.push(643);
        list.push(120);
        
        //100 pushed to stack
        
        list.push(605);
        list.push(639);
        list.push(721);
        list.push(839);
        list.push(196);
        list.push(343);
        list.push(832);
        list.push(620);
        list.push(919);
        list.push(46);
        list.push(506);
        list.push(568);
        list.push(757);
        list.push(673);
        list.push(70);
        list.push(944);
        list.push(11);
        list.push(833);
        list.push(507);
        list.push(991);
        list.push(605);
        list.push(459);
        list.push(218);
        list.push(816);
        list.push(43);
        list.push(78);
        list.push(693);
        list.push(543);
        list.push(845);
        list.push(165);
        list.push(131);
        list.push(787);
        list.push(214);
        list.push(688);
        list.push(250);
        list.push(313);
        list.push(229);
        list.push(295);
        list.push(474);
        list.push(922);
        list.push(614);
        list.push(999);
        list.push(536);
        list.push(879);
        list.push(603);
        list.push(495);
        list.push(971);
        list.push(26);
        list.push(680);
        list.push(347);
        list.push(439);
        list.push(994);
        list.push(621);
        list.push(206);
        list.push(76);
        list.push(596);
        list.push(843);
        list.push(766);
        list.push(73);
        list.push(478);
        list.push(301);
        list.push(598);
        list.push(66);
        list.push(868);
        list.push(179);
        list.push(409);
        list.push(47);
        list.push(713);
        list.push(523);
        list.push(659);
        list.push(410);
        list.push(215);
        list.push(951);
        list.push(815);
        list.push(779);
        list.push(613);
        list.push(23);
        list.push(117);
        list.push(832);
        list.push(784);
        list.push(663);
        list.push(224);
        list.push(643);
        list.push(953);
        list.push(747);
        list.push(756);
        list.push(257);
        list.push(228);
        list.push(931);
        list.push(369);
        list.push(848);
        list.push(189);
        list.push(899);
        list.push(294);
        list.push(687);
        list.push(627);
        list.push(72);
        list.push(436);
        list.push(879);
        list.push(18);
        
        //100 pushed to stack
        
        list.push(245);
        list.push(460);
        list.push(774);
        list.push(52);
        list.push(916);
        list.push(817);
        list.push(32);
        list.push(379);
        list.push(822);
        list.push(331);
        list.push(636);
        list.push(987);
        list.push(778);
        list.push(560);
        list.push(470);
        list.push(894);
        list.push(362);
        list.push(27);
        list.push(437);
        list.push(191);
        list.push(796);
        list.push(762);
        list.push(792);
        list.push(45);
        list.push(143);
        list.push(141);
        list.push(671);
        list.push(623);
        list.push(853);
        list.push(968);
        list.push(697);
        list.push(884);
        list.push(218);
        list.push(330);
        list.push(24);
        list.push(447);
        list.push(826);
        list.push(109);
        list.push(499);
        list.push(216);
        list.push(43);
        list.push(248);
        list.push(627);
        list.push(908);
        list.push(132);
        list.push(95);
        list.push(256);
        list.push(203);
        list.push(637);
        list.push(421);
        list.push(482);
        list.push(134);
        list.push(716);
        list.push(340);
        list.push(190);
        list.push(616);
        list.push(592);
        list.push(13);
        list.push(258);
        list.push(327);
        list.push(518);
        list.push(79);
        list.push(678);
        list.push(504);
        list.push(349);
        list.push(113);
        list.push(433);
        list.push(478);
        list.push(667);
        list.push(770);
        list.push(589);
        list.push(759);
        list.push(901);
        list.push(685);
        list.push(281);
        list.push(366);
        list.push(813);
        list.push(215);
        list.push(631);
        list.push(856);
        list.push(643);
        list.push(301);
        list.push(713);
        list.push(310);
        list.push(900);
        list.push(838);
        list.push(922);
        list.push(724);
        list.push(721);
        list.push(0);
        list.push(403);
        list.push(801);
        list.push(680);
        list.push(148);
        list.push(149);
        list.push(879);
        list.push(457);
        list.push(719);
        list.push(911);
        list.push(223);
        
        //100 pushed to stack
        
        list.push(645);
        list.push(356);
        list.push(681);
        list.push(222);
        list.push(835);
        list.push(464);
        list.push(851);
        list.push(73);
        list.push(784);
        list.push(747);
        list.push(381);
        list.push(316);
        list.push(656);
        list.push(332);
        list.push(324);
        list.push(449);
        list.push(152);
        list.push(394);
        list.push(952);
        list.push(843);
        list.push(12);
        list.push(914);
        list.push(52);
        list.push(763);
        list.push(791);
        list.push(309);
        list.push(837);
        list.push(508);
        list.push(874);
        list.push(226);
        list.push(853);
        list.push(482);
        list.push(424);
        list.push(671);
        list.push(563);
        list.push(399);
        list.push(896);
        list.push(782);
        list.push(974);
        list.push(252);
        list.push(75);
        list.push(578);
        list.push(24);
        list.push(92);
        list.push(431);
        list.push(885);
        list.push(417);
        list.push(373);
        list.push(706);
        list.push(159);
        list.push(515);
        list.push(978);
        list.push(320);
        list.push(315);
        list.push(907);
        list.push(543);
        list.push(533);
        list.push(904);
        list.push(518);
        list.push(35);
        list.push(15);
        list.push(698);
        list.push(217);
        list.push(314);
        list.push(20);
        list.push(566);
        list.push(130);
        list.push(830);
        list.push(103);
        list.push(537);
        list.push(286);
        list.push(96);
        list.push(678);
        list.push(856);
        list.push(821);
        list.push(755);
        list.push(51);
        list.push(515);
        list.push(27);
        list.push(859);
        list.push(349);
        list.push(930);
        list.push(786);
        list.push(473);
        list.push(736);
        list.push(463);
        list.push(770);
        list.push(875);
        list.push(221);
        list.push(448);
        list.push(892);
        list.push(151);
        list.push(434);
        list.push(735);
        list.push(539);
        list.push(581);
        list.push(630);
        list.push(213);
        list.push(862);
        list.push(229);
        //100 pushed to stack
        
        
        
    }//GEN-LAST:event_jbtnStackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnSearch;
    private javax.swing.JButton jbtnStack;
    private javax.swing.JLabel jlblOut;
    private javax.swing.JTextField jtxtIn;
    // End of variables declaration//GEN-END:variables
}
